### PR TITLE
Formalize weight attributes and symbols

### PR DESCRIPTION
**Pull request by ajreynol**
This is towards formalizing weighted grammars in SyGuS.

This introduces term annotations, attributes, weight attributes, and weights for functions to synthesize.

Followup PR will formalize the semantics of weights, then introduce optimization commands.

### CODE REVIEW

**Review by SaswatPadhi — COMMENTED** [review]
Thanks for these changes, Andy.

I have a few comments, but you might already be fixing some of them. I wasn't sure about the best place to inline those, so just listing them here:

1. The grammar is slightly unclear now. If I understand correctly, can we now use `(! t ...)` in place of any term `t` anywhere in any formula?
    - If that's the case, can we redefine the BNF grammar for `<Term>` as, may be:
      ```
      <Term> ::= <AnnotatedTerm> | <UnannotatedTerm>

      <AnnotatedTerm> ::= (! <UnannotatedTerm> <Attribute>+)

      <UnannotatedTerm> ::= /* whatever we currently have for <Term> */
      ```

2. Moreover, could we have a separate section for **Annotations** instead of making it a subsection of **Terms**?
    - You might want to place it _before_ the **Terms** subsection, because we define Literals, Symbols etc. before defining Terms.
    - I think **Weight Annotations** could be made a subsection of the **Annotations** subsection

3. We might want to have a separate subsection for **Keywords** after defining the **Symbols** subsection.
    - There are a bunch of place where we use the `:<something>` syntax, e.g. Features. We might want to refer to these as instances of`<Keyword>`.

**Comment by ajreynol** [comment]
I agree, for point 1, we should add annotated terms to the grammar for terms. I'll do this as another option at the top-level of the term BNF.

For point 2, I was following structure of https://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2021-05-12.pdf.  I think since terms are the only things that can be annotated, it makes sense to have this as a subsection there. 

For 3, good catch, I will refactor a few occurrences of this and the set-feature section.

**Comment by SaswatPadhi** [comment]
> I'll do this as another option at the top-level of the term BNF.

Ah I see, so we can have annotated terms inside other annotated terms as well. Just saw this in the SMTLIB doc.

> I think since terms are the only things that can be annotated, it makes sense to have this as a subsection there.

That's true, annotations only appear on terms. We could keep it as a subsection then.
May be we could rename the "Weight Annotations" subsection to "Attributes" though, and move the last 2 lines of "Term Annotations" subsection to "Attibutes" subsection (following SMTLIB).

**Comment by ajreynol** [comment]
I've committed some updates.  Note that I've made some additions: `declare-weight` is now the way to introduce user-defined weight keywords.  Other parts have been refactored.  I also made a few minor fixes throughout.

**Comment by SaswatPadhi** [comment]
Thanks Andy.

The changes look good to me. There is one TODO, and no examples for the attributes and weights part, but we can go ahead and merge this PR if you want to add those in a separate PR.

This is unrelated to weights and attributes, but on rereading the definitions for features etc again, I found something else confusing:

- We already have `<GrammarDef>?` i.e. optional grammars for `synth-fun`, so what does `:grammar` exactly allow? Is it the case that in a file without `:grammar` feature, `synth-fun` doesn't have the `<GrammarDef>?` part at all?

**Comment by ajreynol** [comment]
Yes, I'll do the rest in a separate PR.

For <GrammarDef>, when `:grammar` is not enabled, then <GrammarDef> is not permitted.  Notice however we state that by default :grammar is enabled, so you'd have to explicitly do `(set-feature :grammar false)` to disable this.

**Pull request merged**
